# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-27 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='showtime',
            field=models.DateField(default=2017-07-27),
            preserve_default=False,
        ),
    ]
