# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-27 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0009_remove_movie_showtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='shows',
            field=models.DateField(default=1983),
        ),
    ]
